force-app/main/default/objects/Allowance__c/Allowance__c.object-meta.xml
<CustomObject>
    <description>Stores all the allowances</description>
    <label>Allowance</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Allowance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allowances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Allowance__c/fields/Allowance_Type__c.field-meta.xml
<CustomField>
    <fullName>Allowance_Type__c</fullName>
    <label>Allowance Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>House Rent Allowance</fullName>
            </value>
            <value>
                <fullName>Internet Allowance</fullName>
            </value>
            <value>
                <fullName>Hybrid Work Allowance</fullName>
            </value>
            <value>
                <fullName>Well Being Allowance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AllowanceTriggerHandler.cls
public with sharing class AllowanceTriggerHandler {

    public static void beforeInsert(List<Allowance__c> newAllowances) {
        //iterate over the allowances
        checkAllowanceThresholds(newAllowances);
    }

    public static void beforeUpdate(Map<Id, Allowance__c> newAllowances, Map<Id, Allowance__c> oldAllowances) {
        List<Allowance__c> allowancesToCheck = new List<Allowance__c>();
        //iterate over the allowances
        for(Allowance__c newAl : newAllowances.values()) {
            Allowance__c oldAl = oldAllowances.get(newAl.Id);
            //check if the amount is changed and 
            if(newAl.Amount__c != oldAl.Amount__c) {
                allowancesToCheck.add(newAl);
            }
        }
        checkAllowanceThresholds(allowancesToCheck);
    }

    private static void checkAllowanceThresholds(List<Allowance__c> allowances) {
        for(Allowance__c al : allowances) {
            //check if the amount is greater than the threshold for the given allowance type
            Decimal threshold = CustomMetadataHelper.getThreshold(al.Allowance_Type__c);
            if(al.Amount__c > threshold) {
                al.addError(Label.Allowance_Threshold_Error + threshold);
            }
        }
    }

}