force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{0000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Amount_Converted_to_USD__c.field-meta.xml
<CustomField>
    <fullName>Amount_Converted_to_USD__c</fullName>
    <label>Amount Converted to USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Amount_Incurred__c.field-meta.xml
<CustomField>
    <fullName>Amount_Incurred__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Amount Incurred</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Currency_Incurred_In__c.field-meta.xml
<CustomField>
    <fullName>Currency_Incurred_In__c</fullName>
    <label>Currency Incurred In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentTriggerHandler.cls
public with sharing class PaymentTriggerHandler {

    public static void beforeInsert(List<Payment__c> newPayments) {
        calculateAmountToUSD(newPayments);
    }

    public static void beforeUpdate(Map<Id, Payment__c> newPayments, Map<Id, Payment__c> oldPayments) {
        List<Payment__c> paymentsToCheck = new List<Payment__c>();
        for(Payment__c pay : newPayments.values()) {
            Decimal oldAmount = oldPayments.get(pay.Id).Amount_Incurred__c;
            String oldCurrency = oldPayments.get(pay.Id).Currency_Incurred_In__c;
            if(pay.Amount_Incurred__c != oldAmount || pay.Currency_Incurred_In__c != oldCurrency) {
                paymentsToCheck.add(pay);
            }
        }
        if(!paymentsToCheck.isEmpty()) {
            calculateAmountToUSD(paymentsToCheck);
        }
    }

    private static void calculateAmountToUSD(List<Payment__c> payments) {
        for(Payment__c pay : payments) {
            if(pay.Amount_Incurred__c == null || pay.Currency_Incurred_In__c == null) {
                pay.addError(Label.Currency_Mandatory);
            } else {
                Decimal crossRate = CustomMetadataHelper.getCurrencyRate(pay.Currency_Incurred_In__c);
                if(crossRate != null) {
                    pay.Amount_Converted_to_USD__c = pay.Amount_Incurred__c/crossRate;
                } 
            }
        }
    }

}